apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
data:
  pgbouncer.ini: |
    [databases]
    * = host=$(PGBOUNCER_DB_HOST) port=$(PGBOUNCER_DB_PORT) dbname=$(PGBOUNCER_DB_NAME)

    [pgbouncer]
    listen_addr = 127.0.0.1
    listen_port = 5432

    pool_mode = transaction
    max_client_conn = 50
    default_pool_size = 10
    min_pool_size = 1
    reserve_pool_size = 2
    reserve_pool_timeout = 3

    server_idle_timeout = 300
    server_lifetime = 1800
    query_wait_timeout = 60
    idle_transaction_timeout = 30

    auth_type = scram-sha-256
    auth_file = /etc/pgbouncer/userlist.txt

    logfile =
    pidfile =
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    verbose = 0
