package reconciliation

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// ReconciliationLag tracks the lag between contract snapshot and backend update for stale snapshots.
	ReconciliationLag = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "reconciliation_lag_seconds",
			Help: "Lag between contract snapshot and backend update in seconds for stale snapshots",
		},
		[]string{"subscription_id"},
	)

	// ReconciliationTotal tracks total reconciliation jobs processed by status.
	ReconciliationTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "reconciliation_jobs_total",
			Help: "Total number of reconciliation jobs processed",
		},
		[]string{"status"}, // status: success, error
	)

	// ReconciliationReportsTotal tracks total reports generated by match status.
	ReconciliationReportsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "reconciliation_reports_total",
			Help: "Total number of reconciliation reports generated",
		},
		[]string{"matched"}, // matched: true, false
	)
)