// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"net/http"
)

// Injectors from wire.go:

// InitializeServer is the wire injector.  The body below is a stub; wire
// replaces it with the generated implementation in wire_gen.go.
//
// The function signature is the public contract:
//   - no inputs – all values come from the provider chain.
//   - returns (*pgxpool.Pool, *http.Server, error) — the pool is needed so
//     main() can drain it during graceful shutdown.
func InitializeServer() (*pgxpool.Pool, *http.Server, error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	engine := ProvideRouter(config)
	pool, err := ProvideDBPool(config)
	if err != nil {
		return nil, nil, err
	}
	server := ProvideHTTPServer(config, engine)
	return pool, server, nil
}

// wire.go:

// AppProviders is the complete set of constructor functions that wire uses to
// resolve the dependency graph.  Adding a new top-level dependency is a
// single-line addition here.
//
//go:generate wire gen .
var AppProviders = wire.NewSet(
	ProvideConfig,
	ProvideRouter,
	ProvideDBPool,
	ProvideHTTPServer,
)
