// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"
)

type Plan struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	AmountCents int64          `json:"amount_cents"`
	Currency    string         `json:"currency"`
	Interval    string         `json:"interval"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Subscription struct {
	ID          string       `json:"id"`
	PlanID      string       `json:"plan_id"`
	Customer    string       `json:"customer"`
	Status      string       `json:"status"`
	AmountCents int64        `json:"amount_cents"`
	Interval    string       `json:"interval"`
	NextBilling sql.NullTime `json:"next_billing"`
	CreatedAt   time.Time    `json:"created_at"`
}
