// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plans.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const deletePlan = `-- name: DeletePlan :execrows
DELETE FROM plans
WHERE id = $1 AND version = $2
`

type DeletePlanParams struct {
	ID      string `json:"id"`
	Version int64  `json:"version"`
}

func (q *Queries) DeletePlan(ctx context.Context, arg DeletePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlan, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findPlanByID = `-- name: FindPlanByID :one
SELECT id, tenant_id, name, amount_cents::text, currency, interval, description, updated_at, version
FROM plans
WHERE id = $1
`

type FindPlanByIDRow struct {
	ID          string         `json:"id"`
	TenantID    string         `json:"tenant_id"`
	Name        string         `json:"name"`
	Amount      string         `json:"amount"`
	Currency    string         `json:"currency"`
	Interval    string         `json:"interval"`
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Version     int64          `json:"version"`
}

func (q *Queries) FindPlanByID(ctx context.Context, id string) (FindPlanByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findPlanByID, id)
	var i FindPlanByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.Description,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, tenant_id, name, amount_cents::text, currency, interval, description, updated_at, version
FROM plans
ORDER BY name, id
`

type ListPlansRow struct {
	ID          string         `json:"id"`
	TenantID    string         `json:"tenant_id"`
	Name        string         `json:"name"`
	Amount      string         `json:"amount"`
	Currency    string         `json:"currency"`
	Interval    string         `json:"interval"`
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Version     int64          `json:"version"`
}

func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.Interval,
			&i.Description,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :execrows
UPDATE plans
SET name = $1, description = $2, version = version + 1
WHERE id = $3 AND version = $4
`

type UpdatePlanParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          string         `json:"id"`
	Version     int64          `json:"version"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlan,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
