// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscriptions.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE id = $1 AND tenant_id = $2 AND version = $3
`

type DeleteSubscriptionParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Version  int64  `json:"version"`
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSubscription, arg.ID, arg.TenantID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findSubscriptionByID = `-- name: FindSubscriptionByID :one
SELECT id, plan_id, tenant_id, customer_id, status, amount, currency, interval,
       next_billing, updated_at, version, deleted_at
FROM subscriptions
WHERE id = $1
`

type FindSubscriptionByIDRow struct {
	ID          string       `json:"id"`
	PlanID      string       `json:"plan_id"`
	TenantID    string       `json:"tenant_id"`
	CustomerID  string       `json:"customer_id"`
	Status      string       `json:"status"`
	Amount      string       `json:"amount"`
	Currency    string       `json:"currency"`
	Interval    string       `json:"interval"`
	NextBilling sql.NullTime `json:"next_billing"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Version     int64        `json:"version"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

func (q *Queries) FindSubscriptionByID(ctx context.Context, id string) (FindSubscriptionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findSubscriptionByID, id)
	var i FindSubscriptionByIDRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.TenantID,
		&i.CustomerID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.NextBilling,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const findSubscriptionByIDAndTenant = `-- name: FindSubscriptionByIDAndTenant :one
SELECT id, plan_id, tenant_id, customer_id, status, amount, currency, interval,
       next_billing, updated_at, version, deleted_at
FROM subscriptions
WHERE id = $1 AND tenant_id = $2
`

type FindSubscriptionByIDAndTenantParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

type FindSubscriptionByIDAndTenantRow struct {
	ID          string       `json:"id"`
	PlanID      string       `json:"plan_id"`
	TenantID    string       `json:"tenant_id"`
	CustomerID  string       `json:"customer_id"`
	Status      string       `json:"status"`
	Amount      string       `json:"amount"`
	Currency    string       `json:"currency"`
	Interval    string       `json:"interval"`
	NextBilling sql.NullTime `json:"next_billing"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Version     int64        `json:"version"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

func (q *Queries) FindSubscriptionByIDAndTenant(ctx context.Context, arg FindSubscriptionByIDAndTenantParams) (FindSubscriptionByIDAndTenantRow, error) {
	row := q.db.QueryRowContext(ctx, findSubscriptionByIDAndTenant, arg.ID, arg.TenantID)
	var i FindSubscriptionByIDAndTenantRow
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.TenantID,
		&i.CustomerID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.Interval,
		&i.NextBilling,
		&i.UpdatedAt,
		&i.Version,
		&i.DeletedAt,
	)
	return i, err
}

const listSubscriptionsByTenant = `-- name: ListSubscriptionsByTenant :many
SELECT id, plan_id, tenant_id, customer_id, status, amount, currency, interval,
       next_billing, updated_at, version, deleted_at
FROM subscriptions
WHERE tenant_id = $1
`

type ListSubscriptionsByTenantRow struct {
	ID          string       `json:"id"`
	PlanID      string       `json:"plan_id"`
	TenantID    string       `json:"tenant_id"`
	CustomerID  string       `json:"customer_id"`
	Status      string       `json:"status"`
	Amount      string       `json:"amount"`
	Currency    string       `json:"currency"`
	Interval    string       `json:"interval"`
	NextBilling sql.NullTime `json:"next_billing"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Version     int64        `json:"version"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListSubscriptionsByTenant(ctx context.Context, tenantID string) ([]ListSubscriptionsByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsByTenantRow
	for rows.Next() {
		var i ListSubscriptionsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.TenantID,
			&i.CustomerID,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.Interval,
			&i.NextBilling,
			&i.UpdatedAt,
			&i.Version,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :execrows
UPDATE subscriptions
SET plan_id = $1, status = $2, amount = $3, currency = $4, interval = $5, next_billing = $6, version = version + 1
WHERE id = $7 AND tenant_id = $8 AND version = $9
`

type UpdateSubscriptionParams struct {
	PlanID      string       `json:"plan_id"`
	Status      string       `json:"status"`
	Amount      string       `json:"amount"`
	Currency    string       `json:"currency"`
	Interval    string       `json:"interval"`
	NextBilling sql.NullTime `json:"next_billing"`
	ID          string       `json:"id"`
	TenantID    string       `json:"tenant_id"`
	Version     int64        `json:"version"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSubscription,
		arg.PlanID,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.Interval,
		arg.NextBilling,
		arg.ID,
		arg.TenantID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :execrows
UPDATE subscriptions
SET status = $1, version = version + 1
WHERE id = $2 AND tenant_id = $3
`

type UpdateSubscriptionStatusParams struct {
	Status   string `json:"status"`
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSubscriptionStatus, arg.Status, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
